# actions can be run locally using act and docker, on Fedora 37 also with podman, using:
# https://github.com/nektos/act
# sudo dnf install -y act-cli podman-docker
# act --bind --container-daemon-socket $XDG_RUNTIME_DIR/podman/podman.sock -W .github/workflows/main.yml

name: Unit tests

# Checks can be skipped by adding "skip-checks: true" to a commit message,
# or requested by adding "request-checks: true" if disabled by default for pushes:
# https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks#skipping-and-requesting-checks-for-individual-commits
on: [push, pull_request]
env:
  PYTHONWARNINGS: "ignore:DEPRECATION"
  PIP_ROOT_USER_ACTION: "ignore"     # For local testing using act-cli
  PIP_NO_WARN_SCRIPT_LOCATION: "0"   # For local testing using act-cli
  PIP_DISABLE_PIP_VERSION_CHECK: "1" # Reduce noise in logs

jobs:
  test:
    strategy:
      # See: https://github.com/xenserver/python-libs/pull/26#discussion_r1179482169
      max-parallel: 1
      # Want to get the results of all the tests, don't terminate all on a fail:
      fail-fast: true
      matrix:
        include:
        # This tests with Python 2.7 and with Ubuntu-20.04's Python 3.8 for combined py2+3 coverage:
        - python-version: '3.6'
          os: ubuntu-20.04
        - python-version: '3.10'
          os: ubuntu-22.04
        - python-version: '3.11'
          os: ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed by diff-cover to get the changed lines: origin/master..HEAD
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python 2.7 using apt-get install
        if: ${{ matrix.python-version == 3.10 }}
        run: apt-get update && apt-get install -y python2-dev

      - name: Run of tox on ubuntu-latest
        if: ${{ startsWith(matrix.python-version, '3.') && matrix.python-version != 3.6 }}
        run: |
          pip install 'virtualenv<20.22' 'tox==4.5.1' tox-gh-actions
          tox --workdir .github/workflows/.tox --recreate

      # tox >= 4.0.0 is needed for using optional-dependencies from pyproject.toml, which is
      # is not available for python <= 3.6, so use the python3.8 of Ubuntu-20.04 to install it:
      - name: Tox on ${{ matrix.os }} (Using 3.8 to use extras from pyproject.toml)
        if: ${{ matrix.python-version == 3.6 }}
        run: |
          set -xv;curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3.8 get-pip.py
          python3.8 -m pip install 'virtualenv<20.22' 'tox==4.5.1'
          tox --workdir .github/workflows/.tox --recreate -e py36-lint-test
