name: Unit tests

on: [push, pull_request]

jobs:
  test_py2:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Pylint
        run: |
          pylint --version
          pylint --exit-zero xcp/ tests/ setup.py
          pylint --exit-zero --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" xcp/ tests/ setup.py > pylint.txt
          diff-quality --violations=pylint --html-report pylint-diff.html pylint.txt

      - uses: actions/upload-artifact@v3
        with:
          name: Pylint diff
          path: pylint-diff.html
