name: Unit tests

on: [push, pull_request]

jobs:
  test_py2:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Pylint
        run: |
          pylint --exit-zero xcp/ tests/ setup.py
